allsettings = {"label_desktop_leaderboard_total": "To Par",
               "label_desktop_leaderboard_holes": "Thru",
               "label_desktop_leaderboard_today": "Today",
               "label_desktop_leaderboard_activity": "Play by play",
               "label_desktop_leaderboard_search_players": "Search Players",
               "label_desktop_leaderboard_cut": "Cut",
               "label_desktop_leaderboard_play_suspended": "Play Suspended",
               "label_desktop_leaderboard_playoff_in_progress": "Playoff in Progress",
               "label_desktop_leaderboard_start_hole_10": "Indicates players who did not start on hole 1",
               "label_desktop_leaderboard_fav_placeholder": "Players you have favourited will appear here",
               "label_desktop_groups_search_players": "Search Players",
               "label_desktop_groups_finished": "F",
               "label_desktop_groups_fav_placeholder": "Players you have favourited will appear here",
               "label_desktop_groups_play_suspended": "Play Suspended",
               "label_desktop_course_follow_hole": "Hole",
               "label_desktop_hole_top": "TOP",
               "label_desktop_hole_grn": "GRN",
               "label_desktop_hole_3d": "3D",
               "label_desktop_hole_rotate": "Rotate",
               "label_desktop_hole_rotate_description": "Left-click and drag to spin and tilt the 3D Map",
               "label_desktop_hole_move": "Move",
               "label_desktop_hole_move_description": "Right-click and drag to move the 3D Map without rotation",
               "label_desktop_hole_zoom": "Zoom",
               "label_desktop_hole_zoom_description": "Use the scroll wheel to control the zoom level",
               "label_desktop_hole_par": "Par",
               "label_desktop_hole_key": "Key",
               "label_desktop_hole_key_albatross": "Albatross",
               "label_desktop_hole_key_eagle": "Eagle",
               "label_desktop_hole_key_birdie": "Birdie",
               "label_desktop_hole_key_par": "Par",
               "label_desktop_hole_key_bogey": "Bogey",
               "label_desktop_hole_key_double_bogey": "D Bogey +",
               "label_desktop_hole_key_tripple_bogey": "Triple Bogey",
               "label_desktop_hole_to_pin": "to Pin",
               "label_desktop_hole_holed": "In the hole for",
               "label_desktop_hole_shot": "SHOT",
               "label_desktop_hole_shots_trails_not_available": "Shots trails are not available on this course",
               "label_desktop_hole_not_yet_played": "Hole not yet played",
               "label_desktop_hole_video_playback_disabled": "Streaming available when logged in with a funded account",
               "label_desktop_scorecard_hole": "Hole",
               "label_desktop_scorecard_par": "Par",
               "label_desktop_scorecard_day": "Day",
               "label_desktop_scorecard_total": "Total",
               "label_desktop_others_ok": "OK",
               "label_desktop_others_wins": "WINS",
               "label_desktop_others_thru": "THRU",
               "label_dictionary_rounds_round": "R",
               "label_dictionary_rounds_playoff": "P",
               "label_dictionary_rounds_knockout_rounds": "Knockout Rounds",
               "label_dictionary_rounds_r16": "Round of 16",
               "label_dictionary_rounds_quarterfinals": "Quarterfinals",
               "label_dictionary_rounds_semifinals": "Semi finals",
               "label_dictionary_rounds_finals": "Finals",
               "label_dictionary_roundStatuses_InProgress": "IN-PLAY",
               "label_dictionary_roundStatuses_NotStarted": "NOT STARTED",
               "label_dictionary_roundStatuses_Official": "FINISHED",
               "label_dictionary_roundStatuses_PlayComplete": "PLAY COMPLETE",
               "label_dictionary_roundStatuses_Cancelled": "CANCELLED",
               "label_dictionary_roundStatuses_Suspended": "SUSPENDED",
               "label_dictionary_position_t": "T<%= position %>",
               "label_dictionary_position_e": "E",
               "label_dictionary_position_dq": "DQ",
               "label_dictionary_position_ret": "RT",
               "label_dictionary_position_wd": "WD",
               "label_dictionary_position_oth": "OTH",
               "label_dictionary_activity_eventNotStarted": "Not Started Yet",
               "label_dictionary_activity_roundStarted": "Not Started Yet",
               "label_dictionary_activity_holeStarted": "At Tee",
               "label_dictionary_activity_approach": "Addressing Ball",
               "label_dictionary_activity_hit": "Hit",
               "label_dictionary_activity_approx": "<%= surface %>",
               "label_dictionary_activity_lie": "<%= distance %>, <%= surface %>",
               "label_dictionary_activity_penalty": "Penalty",
               "label_dictionary_activity_drop": "<%= distance %>, <%= surface %>",
               "label_dictionary_activity_holed": "Ball Holed",
               "label_dictionary_activity_roundFinished": "Round Complete",
               "label_dictionary_activity_hole": "Hole",
               "label_dictionary_activity_shot": "Shot",
               "label_dictionary_activity_notAvailable": "Shot trails not available",
               "label_dictionary_distances_foot": "ft",
               "label_dictionary_distances_feet": "ft",
               "label_dictionary_distances_ft": "ft",
               "label_dictionary_distances_inch": "in.",
               "label_dictionary_distances_inches": "in.",
               "label_dictionary_distances_yds": "yds",
               "OUK": "Unknown",
               "OFW": "Fairway",
               "OGR": "Green",
               "OPT":"N/A",
               "OCO": "Fringe",
               "ORO": "Rough",
               "OIR": "Semi Rough",
               "OWA": "Water",
               "OST": "Bunker",
               "OGS": "Bunker",
               "OTB": "Tee",
               "OOB": "OOB",
               "OTF": "Other Fairway",
               "OTO": "Trees",
               "ODS": "Desert",
               "OBU": "Bushes",
               "OTH": "Other",
               "ONA": "Native Area",
               "OCA": "Cart Path",
               "ODO": "Dirt",
               "OWL":"N/A",
               "HLD": "Holed",
               "label_dictionary_clubTypes_CDW": "Driver",
               "label_dictionary_clubTypes_CFW": "Fairway Wood",
               "label_dictionary_clubTypes_CIR": "Iron",
               "label_dictionary_scoreKeys_font_hole_in_one": "#ff0000",
               "label_dictionary_scoreKeys_background_hole_in_one": "#DDDDDD",
               "label_dictionary_scoreKeys_font_birdie": "#333333",
               "label_dictionary_scoreKeys_background_birdie": "#cfa539",
               "label_dictionary_scoreKeys_font_eagle": "#dddddd",
               "label_dictionary_scoreKeys_background_eagle": "#9c492e",
               "label_dictionary_scoreKeys_font_albatross": "#E4E4E4",
               "label_dictionary_scoreKeys_background_albatross": "#583146",
               "label_dictionary_scoreKeys_font_bogey": "#e4e4e4",
               "label_dictionary_scoreKeys_background_bogey": "#2c3c70",
               "label_dictionary_scoreKeys_font_dbogey": "#ffffff",
               "label_dictionary_scoreKeys_background_dbogey": "#000000",
               "label_dictionary_scoreKeys_font_par": "#dddddd",
               "label_dictionary_scoreKeys_background_par": "#3b5026",
               "label_dictionary_fpc_addressingBall_Base": "is addressing ball",
               "label_dictionary_fpc_addressingBall_Provisional": "is addressing a provisional ball",
               "label_dictionary_fpc_addressingBall_Putt": "is putting for <%= scoringType %>",
               "label_dictionary_fpc_addressingBall_Stroke": ", stroke <%= strokeNo %>",
               "label_dictionary_fpc_addressingBall_Club": ", with <%= clubType %>",
               "label_dictionary_fpc_hitBall_Base": "hits ball",
               "label_dictionary_fpc_hitBall_Putt": "hits putt for <%= scoringType %>",
               "label_dictionary_fpc_hitBall_Stroke": ", stroke <%= strokeNo %>",
               "label_dictionary_fpc_hitBall_Distance": "from <%= distance %>",
               "label_dictionary_fpc_approx_Base": ", to <%= location %>",
               "label_dictionary_fpc_approx_Putt": ", missed putt",
               "label_dictionary_fpc_approx_Stroke": ", stroke <%= strokeNo %>",
               "label_dictionary_fpc_lie_Putt": ", misses putt",
               "label_dictionary_fpc_lie_StrokeDistance": ", <%= strokeDistance %> to <%= location %>",
               "label_dictionary_fpc_lie_DistanceLeft": ", <%= distanceLeft %> left to pin",
               "label_dictionary_fpc_lie_Stroke": ", stroke <%= strokeNo %>",
               "label_dictionary_fpc_lie_Provisional": " (provisional)",
               "label_dictionary_fpc_holed_Base": ", in the hole for <%= scoringType %>",
               "label_dictionary_fpc_drop_Base": ", drops ball to <%= location %>",
               "label_dictionary_fpc_drop_DistanceLeft": ", <%= distance %> left to pin",
               "label_dictionary_fpc_penalty_Base": ", penalty incurred",
               "label_dictionary_fpc_penalty_Stroke": ", stroke <%= strokeNo %>",
               "label_dictionary_fpc_globalComment_Base": "<%= playerName %> just made",
               "label_dictionary_fpc_globalComment_Score": "<%= scoringType %>",
               "label_dictionary_fpc_globalComment_Hole": "on hole <%= holeNo %>",
               "label_dictionary_fpc_shotHistory": "Shot"}
